import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/modules/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ramon Xavier",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <main className="w-full h-full">
          <Header />
          <div
            role="none"
            data-orientation="horizontal"
            className="shrink-0 bg-border h-[1px] w-full"
          />
          {children}
        </main>
      </body>
    </html>
  );
}
